### ISSUE TITLE
repo sync not working under proxy

### ISSUE THREAD

**Issue by deepak-bhagat** [Freescale/fsl-community-bsp-platform#5]
I am tryingto get the project working under proxy. I am able to download all the Pre-requisites installation needed to excute the commands. 
I am able to execute repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b daisy successfully but when I execute the repo sync command i get the following error 
$ repo sync
Fetching project meta-fsl-arm-extra
Fetching project meta-openembedded
Fetching project fsl-community-bsp-base
Fetching project meta-fsl-demos
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection refused

fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection refused

fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection refused

fatal: unable to connect to git.openembedded.org:
git.openembedded.org[0: 140.211.169.152]: errno=Connection refused

fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection refused

fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection refused

fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection refused

fatal: unable to connect to git.openembedded.org:
git.openembedded.org[0: 140.211.169.152]: errno=Connection refused

error: Cannot fetch fsl-community-bsp-base
Fetching project meta-fsl-arm
fatal: unable to connect to git.yoctoproject.org:
git.yoctoproject.org[0: 140.211.169.56]: errno=Connection refused

error: Cannot fetch meta-fsl-demos
error: Cannot fetch meta-fsl-arm-extra
error: Cannot fetch meta-openembedded
fatal: unable to connect to git.yoctoproject.org:
git.yoctoproject.org[0: 140.211.169.56]: errno=Connection refused

error: Cannot fetch meta-fsl-arm

error: Exited sync due to fetch errors

Please can any one help me regarding this issue

**Comment by angolini** [comment]
please, subscribe to the mailing list http://freescale.github.io/#contributing

there are several issues when regarding to the companies proxies. It's virtually impossible to us to really know your proxy configuration and give you any advice how to by-pass that.

You can try to change from http to https, or use http instead of git. Please, contact your IT team in order to know what is allowed and what is denied.
